// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Royal17x/flagr/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockFlagEnvironmentRepository is an autogenerated mock type for the FlagEnvironmentRepository type
type MockFlagEnvironmentRepository struct {
	mock.Mock
}

type MockFlagEnvironmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFlagEnvironmentRepository) EXPECT() *MockFlagEnvironmentRepository_Expecter {
	return &MockFlagEnvironmentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, fe
func (_m *MockFlagEnvironmentRepository) Create(ctx context.Context, fe *domain.FlagEnvironment) (uuid.UUID, error) {
	ret := _m.Called(ctx, fe)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.FlagEnvironment) (uuid.UUID, error)); ok {
		return rf(ctx, fe)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.FlagEnvironment) uuid.UUID); ok {
		r0 = rf(ctx, fe)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.FlagEnvironment) error); ok {
		r1 = rf(ctx, fe)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFlagEnvironmentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFlagEnvironmentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - fe *domain.FlagEnvironment
func (_e *MockFlagEnvironmentRepository_Expecter) Create(ctx interface{}, fe interface{}) *MockFlagEnvironmentRepository_Create_Call {
	return &MockFlagEnvironmentRepository_Create_Call{Call: _e.mock.On("Create", ctx, fe)}
}

func (_c *MockFlagEnvironmentRepository_Create_Call) Run(run func(ctx context.Context, fe *domain.FlagEnvironment)) *MockFlagEnvironmentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.FlagEnvironment))
	})
	return _c
}

func (_c *MockFlagEnvironmentRepository_Create_Call) Return(_a0 uuid.UUID, _a1 error) *MockFlagEnvironmentRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFlagEnvironmentRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.FlagEnvironment) (uuid.UUID, error)) *MockFlagEnvironmentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockFlagEnvironmentRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFlagEnvironmentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFlagEnvironmentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockFlagEnvironmentRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockFlagEnvironmentRepository_Delete_Call {
	return &MockFlagEnvironmentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockFlagEnvironmentRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockFlagEnvironmentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFlagEnvironmentRepository_Delete_Call) Return(_a0 error) *MockFlagEnvironmentRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFlagEnvironmentRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockFlagEnvironmentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByFlagEnvID provides a mock function with given fields: ctx, flagID, envID
func (_m *MockFlagEnvironmentRepository) GetByFlagEnvID(ctx context.Context, flagID uuid.UUID, envID uuid.UUID) (*domain.FlagEnvironment, error) {
	ret := _m.Called(ctx, flagID, envID)

	if len(ret) == 0 {
		panic("no return value specified for GetByFlagEnvID")
	}

	var r0 *domain.FlagEnvironment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.FlagEnvironment, error)); ok {
		return rf(ctx, flagID, envID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.FlagEnvironment); ok {
		r0 = rf(ctx, flagID, envID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FlagEnvironment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, flagID, envID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFlagEnvironmentRepository_GetByFlagEnvID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByFlagEnvID'
type MockFlagEnvironmentRepository_GetByFlagEnvID_Call struct {
	*mock.Call
}

// GetByFlagEnvID is a helper method to define mock.On call
//   - ctx context.Context
//   - flagID uuid.UUID
//   - envID uuid.UUID
func (_e *MockFlagEnvironmentRepository_Expecter) GetByFlagEnvID(ctx interface{}, flagID interface{}, envID interface{}) *MockFlagEnvironmentRepository_GetByFlagEnvID_Call {
	return &MockFlagEnvironmentRepository_GetByFlagEnvID_Call{Call: _e.mock.On("GetByFlagEnvID", ctx, flagID, envID)}
}

func (_c *MockFlagEnvironmentRepository_GetByFlagEnvID_Call) Run(run func(ctx context.Context, flagID uuid.UUID, envID uuid.UUID)) *MockFlagEnvironmentRepository_GetByFlagEnvID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockFlagEnvironmentRepository_GetByFlagEnvID_Call) Return(_a0 *domain.FlagEnvironment, _a1 error) *MockFlagEnvironmentRepository_GetByFlagEnvID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFlagEnvironmentRepository_GetByFlagEnvID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.FlagEnvironment, error)) *MockFlagEnvironmentRepository_GetByFlagEnvID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, flagID
func (_m *MockFlagEnvironmentRepository) List(ctx context.Context, flagID uuid.UUID) ([]*domain.FlagEnvironment, error) {
	ret := _m.Called(ctx, flagID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.FlagEnvironment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.FlagEnvironment, error)); ok {
		return rf(ctx, flagID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.FlagEnvironment); ok {
		r0 = rf(ctx, flagID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.FlagEnvironment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, flagID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFlagEnvironmentRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFlagEnvironmentRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - flagID uuid.UUID
func (_e *MockFlagEnvironmentRepository_Expecter) List(ctx interface{}, flagID interface{}) *MockFlagEnvironmentRepository_List_Call {
	return &MockFlagEnvironmentRepository_List_Call{Call: _e.mock.On("List", ctx, flagID)}
}

func (_c *MockFlagEnvironmentRepository_List_Call) Run(run func(ctx context.Context, flagID uuid.UUID)) *MockFlagEnvironmentRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFlagEnvironmentRepository_List_Call) Return(_a0 []*domain.FlagEnvironment, _a1 error) *MockFlagEnvironmentRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFlagEnvironmentRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.FlagEnvironment, error)) *MockFlagEnvironmentRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, fe
func (_m *MockFlagEnvironmentRepository) Upsert(ctx context.Context, fe *domain.FlagEnvironment) error {
	ret := _m.Called(ctx, fe)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.FlagEnvironment) error); ok {
		r0 = rf(ctx, fe)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFlagEnvironmentRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockFlagEnvironmentRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - fe *domain.FlagEnvironment
func (_e *MockFlagEnvironmentRepository_Expecter) Upsert(ctx interface{}, fe interface{}) *MockFlagEnvironmentRepository_Upsert_Call {
	return &MockFlagEnvironmentRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, fe)}
}

func (_c *MockFlagEnvironmentRepository_Upsert_Call) Run(run func(ctx context.Context, fe *domain.FlagEnvironment)) *MockFlagEnvironmentRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.FlagEnvironment))
	})
	return _c
}

func (_c *MockFlagEnvironmentRepository_Upsert_Call) Return(_a0 error) *MockFlagEnvironmentRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFlagEnvironmentRepository_Upsert_Call) RunAndReturn(run func(context.Context, *domain.FlagEnvironment) error) *MockFlagEnvironmentRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFlagEnvironmentRepository creates a new instance of MockFlagEnvironmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFlagEnvironmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFlagEnvironmentRepository {
	mock := &MockFlagEnvironmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
