// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Royal17x/flagr/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockProjectServiceInterface is an autogenerated mock type for the ProjectServiceInterface type
type MockProjectServiceInterface struct {
	mock.Mock
}

type MockProjectServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectServiceInterface) EXPECT() *MockProjectServiceInterface_Expecter {
	return &MockProjectServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateProject provides a mock function with given fields: ctx, project
func (_m *MockProjectServiceInterface) CreateProject(ctx context.Context, project *domain.Project) (uuid.UUID, error) {
	ret := _m.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Project) (uuid.UUID, error)); ok {
		return rf(ctx, project)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Project) uuid.UUID); ok {
		r0 = rf(ctx, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Project) error); ok {
		r1 = rf(ctx, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectServiceInterface_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type MockProjectServiceInterface_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - project *domain.Project
func (_e *MockProjectServiceInterface_Expecter) CreateProject(ctx interface{}, project interface{}) *MockProjectServiceInterface_CreateProject_Call {
	return &MockProjectServiceInterface_CreateProject_Call{Call: _e.mock.On("CreateProject", ctx, project)}
}

func (_c *MockProjectServiceInterface_CreateProject_Call) Run(run func(ctx context.Context, project *domain.Project)) *MockProjectServiceInterface_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Project))
	})
	return _c
}

func (_c *MockProjectServiceInterface_CreateProject_Call) Return(_a0 uuid.UUID, _a1 error) *MockProjectServiceInterface_CreateProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectServiceInterface_CreateProject_Call) RunAndReturn(run func(context.Context, *domain.Project) (uuid.UUID, error)) *MockProjectServiceInterface_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProject provides a mock function with given fields: ctx, id
func (_m *MockProjectServiceInterface) DeleteProject(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectServiceInterface_DeleteProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProject'
type MockProjectServiceInterface_DeleteProject_Call struct {
	*mock.Call
}

// DeleteProject is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProjectServiceInterface_Expecter) DeleteProject(ctx interface{}, id interface{}) *MockProjectServiceInterface_DeleteProject_Call {
	return &MockProjectServiceInterface_DeleteProject_Call{Call: _e.mock.On("DeleteProject", ctx, id)}
}

func (_c *MockProjectServiceInterface_DeleteProject_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProjectServiceInterface_DeleteProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProjectServiceInterface_DeleteProject_Call) Return(_a0 error) *MockProjectServiceInterface_DeleteProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectServiceInterface_DeleteProject_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockProjectServiceInterface_DeleteProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetProject provides a mock function with given fields: ctx, id
func (_m *MockProjectServiceInterface) GetProject(ctx context.Context, id uuid.UUID) (*domain.Project, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProject")
	}

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Project, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Project); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectServiceInterface_GetProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProject'
type MockProjectServiceInterface_GetProject_Call struct {
	*mock.Call
}

// GetProject is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProjectServiceInterface_Expecter) GetProject(ctx interface{}, id interface{}) *MockProjectServiceInterface_GetProject_Call {
	return &MockProjectServiceInterface_GetProject_Call{Call: _e.mock.On("GetProject", ctx, id)}
}

func (_c *MockProjectServiceInterface_GetProject_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProjectServiceInterface_GetProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProjectServiceInterface_GetProject_Call) Return(_a0 *domain.Project, _a1 error) *MockProjectServiceInterface_GetProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectServiceInterface_GetProject_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Project, error)) *MockProjectServiceInterface_GetProject_Call {
	_c.Call.Return(run)
	return _c
}

// ListProjects provides a mock function with given fields: ctx, orgID
func (_m *MockProjectServiceInterface) ListProjects(ctx context.Context, orgID uuid.UUID) ([]*domain.Project, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListProjects")
	}

	var r0 []*domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Project, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Project); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectServiceInterface_ListProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProjects'
type MockProjectServiceInterface_ListProjects_Call struct {
	*mock.Call
}

// ListProjects is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
func (_e *MockProjectServiceInterface_Expecter) ListProjects(ctx interface{}, orgID interface{}) *MockProjectServiceInterface_ListProjects_Call {
	return &MockProjectServiceInterface_ListProjects_Call{Call: _e.mock.On("ListProjects", ctx, orgID)}
}

func (_c *MockProjectServiceInterface_ListProjects_Call) Run(run func(ctx context.Context, orgID uuid.UUID)) *MockProjectServiceInterface_ListProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProjectServiceInterface_ListProjects_Call) Return(_a0 []*domain.Project, _a1 error) *MockProjectServiceInterface_ListProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectServiceInterface_ListProjects_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.Project, error)) *MockProjectServiceInterface_ListProjects_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProject provides a mock function with given fields: ctx, project
func (_m *MockProjectServiceInterface) UpdateProject(ctx context.Context, project *domain.Project) error {
	ret := _m.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Project) error); ok {
		r0 = rf(ctx, project)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectServiceInterface_UpdateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProject'
type MockProjectServiceInterface_UpdateProject_Call struct {
	*mock.Call
}

// UpdateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - project *domain.Project
func (_e *MockProjectServiceInterface_Expecter) UpdateProject(ctx interface{}, project interface{}) *MockProjectServiceInterface_UpdateProject_Call {
	return &MockProjectServiceInterface_UpdateProject_Call{Call: _e.mock.On("UpdateProject", ctx, project)}
}

func (_c *MockProjectServiceInterface_UpdateProject_Call) Run(run func(ctx context.Context, project *domain.Project)) *MockProjectServiceInterface_UpdateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Project))
	})
	return _c
}

func (_c *MockProjectServiceInterface_UpdateProject_Call) Return(_a0 error) *MockProjectServiceInterface_UpdateProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectServiceInterface_UpdateProject_Call) RunAndReturn(run func(context.Context, *domain.Project) error) *MockProjectServiceInterface_UpdateProject_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectServiceInterface creates a new instance of MockProjectServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectServiceInterface {
	mock := &MockProjectServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
