// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Royal17x/flagr/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockFlagServiceInterface is an autogenerated mock type for the FlagServiceInterface type
type MockFlagServiceInterface struct {
	mock.Mock
}

type MockFlagServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFlagServiceInterface) EXPECT() *MockFlagServiceInterface_Expecter {
	return &MockFlagServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateFlag provides a mock function with given fields: ctx, flag
func (_m *MockFlagServiceInterface) CreateFlag(ctx context.Context, flag *domain.Flag) (uuid.UUID, error) {
	ret := _m.Called(ctx, flag)

	if len(ret) == 0 {
		panic("no return value specified for CreateFlag")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Flag) (uuid.UUID, error)); ok {
		return rf(ctx, flag)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Flag) uuid.UUID); ok {
		r0 = rf(ctx, flag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Flag) error); ok {
		r1 = rf(ctx, flag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFlagServiceInterface_CreateFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFlag'
type MockFlagServiceInterface_CreateFlag_Call struct {
	*mock.Call
}

// CreateFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - flag *domain.Flag
func (_e *MockFlagServiceInterface_Expecter) CreateFlag(ctx interface{}, flag interface{}) *MockFlagServiceInterface_CreateFlag_Call {
	return &MockFlagServiceInterface_CreateFlag_Call{Call: _e.mock.On("CreateFlag", ctx, flag)}
}

func (_c *MockFlagServiceInterface_CreateFlag_Call) Run(run func(ctx context.Context, flag *domain.Flag)) *MockFlagServiceInterface_CreateFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Flag))
	})
	return _c
}

func (_c *MockFlagServiceInterface_CreateFlag_Call) Return(_a0 uuid.UUID, _a1 error) *MockFlagServiceInterface_CreateFlag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFlagServiceInterface_CreateFlag_Call) RunAndReturn(run func(context.Context, *domain.Flag) (uuid.UUID, error)) *MockFlagServiceInterface_CreateFlag_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFlag provides a mock function with given fields: ctx, id
func (_m *MockFlagServiceInterface) DeleteFlag(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFlag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFlagServiceInterface_DeleteFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFlag'
type MockFlagServiceInterface_DeleteFlag_Call struct {
	*mock.Call
}

// DeleteFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockFlagServiceInterface_Expecter) DeleteFlag(ctx interface{}, id interface{}) *MockFlagServiceInterface_DeleteFlag_Call {
	return &MockFlagServiceInterface_DeleteFlag_Call{Call: _e.mock.On("DeleteFlag", ctx, id)}
}

func (_c *MockFlagServiceInterface_DeleteFlag_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockFlagServiceInterface_DeleteFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFlagServiceInterface_DeleteFlag_Call) Return(_a0 error) *MockFlagServiceInterface_DeleteFlag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFlagServiceInterface_DeleteFlag_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockFlagServiceInterface_DeleteFlag_Call {
	_c.Call.Return(run)
	return _c
}

// EvaluateFlag provides a mock function with given fields: ctx, flagKey, projectID, environmentID
func (_m *MockFlagServiceInterface) EvaluateFlag(ctx context.Context, flagKey string, projectID uuid.UUID, environmentID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, flagKey, projectID, environmentID)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateFlag")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, flagKey, projectID, environmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, flagKey, projectID, environmentID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, flagKey, projectID, environmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFlagServiceInterface_EvaluateFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluateFlag'
type MockFlagServiceInterface_EvaluateFlag_Call struct {
	*mock.Call
}

// EvaluateFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - flagKey string
//   - projectID uuid.UUID
//   - environmentID uuid.UUID
func (_e *MockFlagServiceInterface_Expecter) EvaluateFlag(ctx interface{}, flagKey interface{}, projectID interface{}, environmentID interface{}) *MockFlagServiceInterface_EvaluateFlag_Call {
	return &MockFlagServiceInterface_EvaluateFlag_Call{Call: _e.mock.On("EvaluateFlag", ctx, flagKey, projectID, environmentID)}
}

func (_c *MockFlagServiceInterface_EvaluateFlag_Call) Run(run func(ctx context.Context, flagKey string, projectID uuid.UUID, environmentID uuid.UUID)) *MockFlagServiceInterface_EvaluateFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockFlagServiceInterface_EvaluateFlag_Call) Return(_a0 bool, _a1 error) *MockFlagServiceInterface_EvaluateFlag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFlagServiceInterface_EvaluateFlag_Call) RunAndReturn(run func(context.Context, string, uuid.UUID, uuid.UUID) (bool, error)) *MockFlagServiceInterface_EvaluateFlag_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlag provides a mock function with given fields: ctx, id
func (_m *MockFlagServiceInterface) GetFlag(ctx context.Context, id uuid.UUID) (*domain.Flag, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFlag")
	}

	var r0 *domain.Flag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Flag, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Flag); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Flag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFlagServiceInterface_GetFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlag'
type MockFlagServiceInterface_GetFlag_Call struct {
	*mock.Call
}

// GetFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockFlagServiceInterface_Expecter) GetFlag(ctx interface{}, id interface{}) *MockFlagServiceInterface_GetFlag_Call {
	return &MockFlagServiceInterface_GetFlag_Call{Call: _e.mock.On("GetFlag", ctx, id)}
}

func (_c *MockFlagServiceInterface_GetFlag_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockFlagServiceInterface_GetFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFlagServiceInterface_GetFlag_Call) Return(_a0 *domain.Flag, _a1 error) *MockFlagServiceInterface_GetFlag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFlagServiceInterface_GetFlag_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Flag, error)) *MockFlagServiceInterface_GetFlag_Call {
	_c.Call.Return(run)
	return _c
}

// ListFlags provides a mock function with given fields: ctx, projectID
func (_m *MockFlagServiceInterface) ListFlags(ctx context.Context, projectID uuid.UUID) ([]*domain.Flag, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for ListFlags")
	}

	var r0 []*domain.Flag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Flag, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Flag); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Flag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFlagServiceInterface_ListFlags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFlags'
type MockFlagServiceInterface_ListFlags_Call struct {
	*mock.Call
}

// ListFlags is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
func (_e *MockFlagServiceInterface_Expecter) ListFlags(ctx interface{}, projectID interface{}) *MockFlagServiceInterface_ListFlags_Call {
	return &MockFlagServiceInterface_ListFlags_Call{Call: _e.mock.On("ListFlags", ctx, projectID)}
}

func (_c *MockFlagServiceInterface_ListFlags_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockFlagServiceInterface_ListFlags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFlagServiceInterface_ListFlags_Call) Return(_a0 []*domain.Flag, _a1 error) *MockFlagServiceInterface_ListFlags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFlagServiceInterface_ListFlags_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.Flag, error)) *MockFlagServiceInterface_ListFlags_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFlag provides a mock function with given fields: ctx, flag
func (_m *MockFlagServiceInterface) UpdateFlag(ctx context.Context, flag *domain.Flag) error {
	ret := _m.Called(ctx, flag)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFlag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Flag) error); ok {
		r0 = rf(ctx, flag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFlagServiceInterface_UpdateFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFlag'
type MockFlagServiceInterface_UpdateFlag_Call struct {
	*mock.Call
}

// UpdateFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - flag *domain.Flag
func (_e *MockFlagServiceInterface_Expecter) UpdateFlag(ctx interface{}, flag interface{}) *MockFlagServiceInterface_UpdateFlag_Call {
	return &MockFlagServiceInterface_UpdateFlag_Call{Call: _e.mock.On("UpdateFlag", ctx, flag)}
}

func (_c *MockFlagServiceInterface_UpdateFlag_Call) Run(run func(ctx context.Context, flag *domain.Flag)) *MockFlagServiceInterface_UpdateFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Flag))
	})
	return _c
}

func (_c *MockFlagServiceInterface_UpdateFlag_Call) Return(_a0 error) *MockFlagServiceInterface_UpdateFlag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFlagServiceInterface_UpdateFlag_Call) RunAndReturn(run func(context.Context, *domain.Flag) error) *MockFlagServiceInterface_UpdateFlag_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFlagServiceInterface creates a new instance of MockFlagServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFlagServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFlagServiceInterface {
	mock := &MockFlagServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
