// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Royal17x/flagr/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockProjectRepository is an autogenerated mock type for the ProjectRepository type
type MockProjectRepository struct {
	mock.Mock
}

type MockProjectRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectRepository) EXPECT() *MockProjectRepository_Expecter {
	return &MockProjectRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, project
func (_m *MockProjectRepository) Create(ctx context.Context, project *domain.Project) (uuid.UUID, error) {
	ret := _m.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Project) (uuid.UUID, error)); ok {
		return rf(ctx, project)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Project) uuid.UUID); ok {
		r0 = rf(ctx, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Project) error); ok {
		r1 = rf(ctx, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProjectRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - project *domain.Project
func (_e *MockProjectRepository_Expecter) Create(ctx interface{}, project interface{}) *MockProjectRepository_Create_Call {
	return &MockProjectRepository_Create_Call{Call: _e.mock.On("Create", ctx, project)}
}

func (_c *MockProjectRepository_Create_Call) Run(run func(ctx context.Context, project *domain.Project)) *MockProjectRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Project))
	})
	return _c
}

func (_c *MockProjectRepository_Create_Call) Return(_a0 uuid.UUID, _a1 error) *MockProjectRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Project) (uuid.UUID, error)) *MockProjectRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockProjectRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProjectRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProjectRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockProjectRepository_Delete_Call {
	return &MockProjectRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockProjectRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProjectRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProjectRepository_Delete_Call) Return(_a0 error) *MockProjectRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockProjectRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockProjectRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Project, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Project, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Project); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProjectRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProjectRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockProjectRepository_GetByID_Call {
	return &MockProjectRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockProjectRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProjectRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProjectRepository_GetByID_Call) Return(_a0 *domain.Project, _a1 error) *MockProjectRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Project, error)) *MockProjectRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, orgID
func (_m *MockProjectRepository) List(ctx context.Context, orgID uuid.UUID) ([]*domain.Project, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Project, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Project); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockProjectRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
func (_e *MockProjectRepository_Expecter) List(ctx interface{}, orgID interface{}) *MockProjectRepository_List_Call {
	return &MockProjectRepository_List_Call{Call: _e.mock.On("List", ctx, orgID)}
}

func (_c *MockProjectRepository_List_Call) Run(run func(ctx context.Context, orgID uuid.UUID)) *MockProjectRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProjectRepository_List_Call) Return(_a0 []*domain.Project, _a1 error) *MockProjectRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.Project, error)) *MockProjectRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, project
func (_m *MockProjectRepository) Update(ctx context.Context, project *domain.Project) error {
	ret := _m.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Project) error); ok {
		r0 = rf(ctx, project)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProjectRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - project *domain.Project
func (_e *MockProjectRepository_Expecter) Update(ctx interface{}, project interface{}) *MockProjectRepository_Update_Call {
	return &MockProjectRepository_Update_Call{Call: _e.mock.On("Update", ctx, project)}
}

func (_c *MockProjectRepository_Update_Call) Run(run func(ctx context.Context, project *domain.Project)) *MockProjectRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Project))
	})
	return _c
}

func (_c *MockProjectRepository_Update_Call) Return(_a0 error) *MockProjectRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Project) error) *MockProjectRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectRepository creates a new instance of MockProjectRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectRepository {
	mock := &MockProjectRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
