// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Royal17x/flagr/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockEnvironmentServiceInterface is an autogenerated mock type for the EnvironmentServiceInterface type
type MockEnvironmentServiceInterface struct {
	mock.Mock
}

type MockEnvironmentServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnvironmentServiceInterface) EXPECT() *MockEnvironmentServiceInterface_Expecter {
	return &MockEnvironmentServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateEnvironment provides a mock function with given fields: ctx, env
func (_m *MockEnvironmentServiceInterface) CreateEnvironment(ctx context.Context, env *domain.Environment) (uuid.UUID, error) {
	ret := _m.Called(ctx, env)

	if len(ret) == 0 {
		panic("no return value specified for CreateEnvironment")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Environment) (uuid.UUID, error)); ok {
		return rf(ctx, env)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Environment) uuid.UUID); ok {
		r0 = rf(ctx, env)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Environment) error); ok {
		r1 = rf(ctx, env)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEnvironmentServiceInterface_CreateEnvironment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEnvironment'
type MockEnvironmentServiceInterface_CreateEnvironment_Call struct {
	*mock.Call
}

// CreateEnvironment is a helper method to define mock.On call
//   - ctx context.Context
//   - env *domain.Environment
func (_e *MockEnvironmentServiceInterface_Expecter) CreateEnvironment(ctx interface{}, env interface{}) *MockEnvironmentServiceInterface_CreateEnvironment_Call {
	return &MockEnvironmentServiceInterface_CreateEnvironment_Call{Call: _e.mock.On("CreateEnvironment", ctx, env)}
}

func (_c *MockEnvironmentServiceInterface_CreateEnvironment_Call) Run(run func(ctx context.Context, env *domain.Environment)) *MockEnvironmentServiceInterface_CreateEnvironment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Environment))
	})
	return _c
}

func (_c *MockEnvironmentServiceInterface_CreateEnvironment_Call) Return(_a0 uuid.UUID, _a1 error) *MockEnvironmentServiceInterface_CreateEnvironment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEnvironmentServiceInterface_CreateEnvironment_Call) RunAndReturn(run func(context.Context, *domain.Environment) (uuid.UUID, error)) *MockEnvironmentServiceInterface_CreateEnvironment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEnvironment provides a mock function with given fields: ctx, id
func (_m *MockEnvironmentServiceInterface) DeleteEnvironment(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEnvironment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEnvironmentServiceInterface_DeleteEnvironment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEnvironment'
type MockEnvironmentServiceInterface_DeleteEnvironment_Call struct {
	*mock.Call
}

// DeleteEnvironment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockEnvironmentServiceInterface_Expecter) DeleteEnvironment(ctx interface{}, id interface{}) *MockEnvironmentServiceInterface_DeleteEnvironment_Call {
	return &MockEnvironmentServiceInterface_DeleteEnvironment_Call{Call: _e.mock.On("DeleteEnvironment", ctx, id)}
}

func (_c *MockEnvironmentServiceInterface_DeleteEnvironment_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockEnvironmentServiceInterface_DeleteEnvironment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockEnvironmentServiceInterface_DeleteEnvironment_Call) Return(_a0 error) *MockEnvironmentServiceInterface_DeleteEnvironment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEnvironmentServiceInterface_DeleteEnvironment_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockEnvironmentServiceInterface_DeleteEnvironment_Call {
	_c.Call.Return(run)
	return _c
}

// ListEnvironments provides a mock function with given fields: ctx, projectID
func (_m *MockEnvironmentServiceInterface) ListEnvironments(ctx context.Context, projectID uuid.UUID) ([]*domain.Environment, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for ListEnvironments")
	}

	var r0 []*domain.Environment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Environment, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Environment); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Environment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEnvironmentServiceInterface_ListEnvironments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEnvironments'
type MockEnvironmentServiceInterface_ListEnvironments_Call struct {
	*mock.Call
}

// ListEnvironments is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
func (_e *MockEnvironmentServiceInterface_Expecter) ListEnvironments(ctx interface{}, projectID interface{}) *MockEnvironmentServiceInterface_ListEnvironments_Call {
	return &MockEnvironmentServiceInterface_ListEnvironments_Call{Call: _e.mock.On("ListEnvironments", ctx, projectID)}
}

func (_c *MockEnvironmentServiceInterface_ListEnvironments_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockEnvironmentServiceInterface_ListEnvironments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockEnvironmentServiceInterface_ListEnvironments_Call) Return(_a0 []*domain.Environment, _a1 error) *MockEnvironmentServiceInterface_ListEnvironments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEnvironmentServiceInterface_ListEnvironments_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.Environment, error)) *MockEnvironmentServiceInterface_ListEnvironments_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEnvironmentServiceInterface creates a new instance of MockEnvironmentServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnvironmentServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnvironmentServiceInterface {
	mock := &MockEnvironmentServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
