// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Royal17x/flagr/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, token
func (_m *MockRefreshTokenRepository) Create(ctx context.Context, token *domain.RefreshToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RefreshToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.RefreshToken
func (_e *MockRefreshTokenRepository_Expecter) Create(ctx interface{}, token interface{}) *MockRefreshTokenRepository_Create_Call {
	return &MockRefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *MockRefreshTokenRepository_Create_Call) Run(run func(ctx context.Context, token *domain.RefreshToken)) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.RefreshToken))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) Return(_a0 error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.RefreshToken) error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllByUserID provides a mock function with given fields: ctx, userID
func (_m *MockRefreshTokenRepository) DeleteAllByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_DeleteAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllByUserID'
type MockRefreshTokenRepository_DeleteAllByUserID_Call struct {
	*mock.Call
}

// DeleteAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockRefreshTokenRepository_Expecter) DeleteAllByUserID(ctx interface{}, userID interface{}) *MockRefreshTokenRepository_DeleteAllByUserID_Call {
	return &MockRefreshTokenRepository_DeleteAllByUserID_Call{Call: _e.mock.On("DeleteAllByUserID", ctx, userID)}
}

func (_c *MockRefreshTokenRepository_DeleteAllByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockRefreshTokenRepository_DeleteAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteAllByUserID_Call) Return(_a0 error) *MockRefreshTokenRepository_DeleteAllByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteAllByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockRefreshTokenRepository_DeleteAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByTokenHash provides a mock function with given fields: ctx, hash
func (_m *MockRefreshTokenRepository) DeleteByTokenHash(ctx context.Context, hash string) error {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByTokenHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, hash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_DeleteByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByTokenHash'
type MockRefreshTokenRepository_DeleteByTokenHash_Call struct {
	*mock.Call
}

// DeleteByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockRefreshTokenRepository_Expecter) DeleteByTokenHash(ctx interface{}, hash interface{}) *MockRefreshTokenRepository_DeleteByTokenHash_Call {
	return &MockRefreshTokenRepository_DeleteByTokenHash_Call{Call: _e.mock.On("DeleteByTokenHash", ctx, hash)}
}

func (_c *MockRefreshTokenRepository_DeleteByTokenHash_Call) Run(run func(ctx context.Context, hash string)) *MockRefreshTokenRepository_DeleteByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteByTokenHash_Call) Return(_a0 error) *MockRefreshTokenRepository_DeleteByTokenHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteByTokenHash_Call) RunAndReturn(run func(context.Context, string) error) *MockRefreshTokenRepository_DeleteByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTokenHash provides a mock function with given fields: ctx, hash
func (_m *MockRefreshTokenRepository) GetByTokenHash(ctx context.Context, hash string) (*domain.RefreshToken, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenHash")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.RefreshToken, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.RefreshToken); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_GetByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTokenHash'
type MockRefreshTokenRepository_GetByTokenHash_Call struct {
	*mock.Call
}

// GetByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockRefreshTokenRepository_Expecter) GetByTokenHash(ctx interface{}, hash interface{}) *MockRefreshTokenRepository_GetByTokenHash_Call {
	return &MockRefreshTokenRepository_GetByTokenHash_Call{Call: _e.mock.On("GetByTokenHash", ctx, hash)}
}

func (_c *MockRefreshTokenRepository_GetByTokenHash_Call) Run(run func(ctx context.Context, hash string)) *MockRefreshTokenRepository_GetByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_GetByTokenHash_Call) Return(_a0 *domain.RefreshToken, _a1 error) *MockRefreshTokenRepository_GetByTokenHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_GetByTokenHash_Call) RunAndReturn(run func(context.Context, string) (*domain.RefreshToken, error)) *MockRefreshTokenRepository_GetByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
