// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Royal17x/flagr/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockEnvironmentRepository is an autogenerated mock type for the EnvironmentRepository type
type MockEnvironmentRepository struct {
	mock.Mock
}

type MockEnvironmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnvironmentRepository) EXPECT() *MockEnvironmentRepository_Expecter {
	return &MockEnvironmentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, env
func (_m *MockEnvironmentRepository) Create(ctx context.Context, env *domain.Environment) (uuid.UUID, error) {
	ret := _m.Called(ctx, env)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Environment) (uuid.UUID, error)); ok {
		return rf(ctx, env)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Environment) uuid.UUID); ok {
		r0 = rf(ctx, env)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Environment) error); ok {
		r1 = rf(ctx, env)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEnvironmentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEnvironmentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - env *domain.Environment
func (_e *MockEnvironmentRepository_Expecter) Create(ctx interface{}, env interface{}) *MockEnvironmentRepository_Create_Call {
	return &MockEnvironmentRepository_Create_Call{Call: _e.mock.On("Create", ctx, env)}
}

func (_c *MockEnvironmentRepository_Create_Call) Run(run func(ctx context.Context, env *domain.Environment)) *MockEnvironmentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Environment))
	})
	return _c
}

func (_c *MockEnvironmentRepository_Create_Call) Return(_a0 uuid.UUID, _a1 error) *MockEnvironmentRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEnvironmentRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Environment) (uuid.UUID, error)) *MockEnvironmentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockEnvironmentRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEnvironmentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEnvironmentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockEnvironmentRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockEnvironmentRepository_Delete_Call {
	return &MockEnvironmentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockEnvironmentRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockEnvironmentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockEnvironmentRepository_Delete_Call) Return(_a0 error) *MockEnvironmentRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEnvironmentRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockEnvironmentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProjectID provides a mock function with given fields: ctx, projectID
func (_m *MockEnvironmentRepository) GetByProjectID(ctx context.Context, projectID uuid.UUID) (*domain.Environment, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetByProjectID")
	}

	var r0 *domain.Environment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Environment, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Environment); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Environment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEnvironmentRepository_GetByProjectID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProjectID'
type MockEnvironmentRepository_GetByProjectID_Call struct {
	*mock.Call
}

// GetByProjectID is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
func (_e *MockEnvironmentRepository_Expecter) GetByProjectID(ctx interface{}, projectID interface{}) *MockEnvironmentRepository_GetByProjectID_Call {
	return &MockEnvironmentRepository_GetByProjectID_Call{Call: _e.mock.On("GetByProjectID", ctx, projectID)}
}

func (_c *MockEnvironmentRepository_GetByProjectID_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockEnvironmentRepository_GetByProjectID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockEnvironmentRepository_GetByProjectID_Call) Return(_a0 *domain.Environment, _a1 error) *MockEnvironmentRepository_GetByProjectID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEnvironmentRepository_GetByProjectID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Environment, error)) *MockEnvironmentRepository_GetByProjectID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, projectID
func (_m *MockEnvironmentRepository) List(ctx context.Context, projectID uuid.UUID) ([]*domain.Environment, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Environment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Environment, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Environment); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Environment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEnvironmentRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockEnvironmentRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
func (_e *MockEnvironmentRepository_Expecter) List(ctx interface{}, projectID interface{}) *MockEnvironmentRepository_List_Call {
	return &MockEnvironmentRepository_List_Call{Call: _e.mock.On("List", ctx, projectID)}
}

func (_c *MockEnvironmentRepository_List_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockEnvironmentRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockEnvironmentRepository_List_Call) Return(_a0 []*domain.Environment, _a1 error) *MockEnvironmentRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEnvironmentRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.Environment, error)) *MockEnvironmentRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, env
func (_m *MockEnvironmentRepository) Update(ctx context.Context, env *domain.Environment) error {
	ret := _m.Called(ctx, env)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Environment) error); ok {
		r0 = rf(ctx, env)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEnvironmentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockEnvironmentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - env *domain.Environment
func (_e *MockEnvironmentRepository_Expecter) Update(ctx interface{}, env interface{}) *MockEnvironmentRepository_Update_Call {
	return &MockEnvironmentRepository_Update_Call{Call: _e.mock.On("Update", ctx, env)}
}

func (_c *MockEnvironmentRepository_Update_Call) Run(run func(ctx context.Context, env *domain.Environment)) *MockEnvironmentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Environment))
	})
	return _c
}

func (_c *MockEnvironmentRepository_Update_Call) Return(_a0 error) *MockEnvironmentRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEnvironmentRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Environment) error) *MockEnvironmentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEnvironmentRepository creates a new instance of MockEnvironmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnvironmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnvironmentRepository {
	mock := &MockEnvironmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
