// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/Royal17x/flagr/backend/internal/service"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAuthServiceInterface is an autogenerated mock type for the AuthServiceInterface type
type MockAuthServiceInterface struct {
	mock.Mock
}

type MockAuthServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterface_Expecter {
	return &MockAuthServiceInterface_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *MockAuthServiceInterface) Login(ctx context.Context, email string, password string) (service.TokenPair, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 service.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (service.TokenPair, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) service.TokenPair); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(service.TokenPair)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceInterface_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthServiceInterface_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockAuthServiceInterface_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *MockAuthServiceInterface_Login_Call {
	return &MockAuthServiceInterface_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockAuthServiceInterface_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockAuthServiceInterface_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_Login_Call) Return(_a0 service.TokenPair, _a1 error) *MockAuthServiceInterface_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceInterface_Login_Call) RunAndReturn(run func(context.Context, string, string) (service.TokenPair, error)) *MockAuthServiceInterface_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, refreshToken
func (_m *MockAuthServiceInterface) Logout(ctx context.Context, refreshToken string) error {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServiceInterface_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthServiceInterface_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthServiceInterface_Expecter) Logout(ctx interface{}, refreshToken interface{}) *MockAuthServiceInterface_Logout_Call {
	return &MockAuthServiceInterface_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *MockAuthServiceInterface_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthServiceInterface_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_Logout_Call) Return(_a0 error) *MockAuthServiceInterface_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServiceInterface_Logout_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthServiceInterface_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, refreshToken
func (_m *MockAuthServiceInterface) Refresh(ctx context.Context, refreshToken string) (service.TokenPair, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 service.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (service.TokenPair, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) service.TokenPair); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(service.TokenPair)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceInterface_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockAuthServiceInterface_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthServiceInterface_Expecter) Refresh(ctx interface{}, refreshToken interface{}) *MockAuthServiceInterface_Refresh_Call {
	return &MockAuthServiceInterface_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshToken)}
}

func (_c *MockAuthServiceInterface_Refresh_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthServiceInterface_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_Refresh_Call) Return(_a0 service.TokenPair, _a1 error) *MockAuthServiceInterface_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceInterface_Refresh_Call) RunAndReturn(run func(context.Context, string) (service.TokenPair, error)) *MockAuthServiceInterface_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, email, password, orgID
func (_m *MockAuthServiceInterface) Register(ctx context.Context, email string, password string, orgID uuid.UUID) (service.TokenPair, error) {
	ret := _m.Called(ctx, email, password, orgID)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 service.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID) (service.TokenPair, error)); ok {
		return rf(ctx, email, password, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID) service.TokenPair); ok {
		r0 = rf(ctx, email, password, orgID)
	} else {
		r0 = ret.Get(0).(service.TokenPair)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, uuid.UUID) error); ok {
		r1 = rf(ctx, email, password, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceInterface_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthServiceInterface_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - orgID uuid.UUID
func (_e *MockAuthServiceInterface_Expecter) Register(ctx interface{}, email interface{}, password interface{}, orgID interface{}) *MockAuthServiceInterface_Register_Call {
	return &MockAuthServiceInterface_Register_Call{Call: _e.mock.On("Register", ctx, email, password, orgID)}
}

func (_c *MockAuthServiceInterface_Register_Call) Run(run func(ctx context.Context, email string, password string, orgID uuid.UUID)) *MockAuthServiceInterface_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthServiceInterface_Register_Call) Return(_a0 service.TokenPair, _a1 error) *MockAuthServiceInterface_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceInterface_Register_Call) RunAndReturn(run func(context.Context, string, string, uuid.UUID) (service.TokenPair, error)) *MockAuthServiceInterface_Register_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function with given fields: tokenStr
func (_m *MockAuthServiceInterface) ValidateAccessToken(tokenStr string) (*service.Claims, error) {
	ret := _m.Called(tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *service.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*service.Claims, error)); ok {
		return rf(tokenStr)
	}
	if rf, ok := ret.Get(0).(func(string) *service.Claims); ok {
		r0 = rf(tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceInterface_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockAuthServiceInterface_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - tokenStr string
func (_e *MockAuthServiceInterface_Expecter) ValidateAccessToken(tokenStr interface{}) *MockAuthServiceInterface_ValidateAccessToken_Call {
	return &MockAuthServiceInterface_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", tokenStr)}
}

func (_c *MockAuthServiceInterface_ValidateAccessToken_Call) Run(run func(tokenStr string)) *MockAuthServiceInterface_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_ValidateAccessToken_Call) Return(_a0 *service.Claims, _a1 error) *MockAuthServiceInterface_ValidateAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceInterface_ValidateAccessToken_Call) RunAndReturn(run func(string) (*service.Claims, error)) *MockAuthServiceInterface_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthServiceInterface creates a new instance of MockAuthServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
