// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockFlagCache is an autogenerated mock type for the FlagCache type
type MockFlagCache struct {
	mock.Mock
}

type MockFlagCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFlagCache) EXPECT() *MockFlagCache_Expecter {
	return &MockFlagCache_Expecter{mock: &_m.Mock}
}

// GetEvaluation provides a mock function with given fields: ctx, flagKey, projectID, envID
func (_m *MockFlagCache) GetEvaluation(ctx context.Context, flagKey string, projectID uuid.UUID, envID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, flagKey, projectID, envID)

	if len(ret) == 0 {
		panic("no return value specified for GetEvaluation")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, flagKey, projectID, envID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, flagKey, projectID, envID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, flagKey, projectID, envID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFlagCache_GetEvaluation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvaluation'
type MockFlagCache_GetEvaluation_Call struct {
	*mock.Call
}

// GetEvaluation is a helper method to define mock.On call
//   - ctx context.Context
//   - flagKey string
//   - projectID uuid.UUID
//   - envID uuid.UUID
func (_e *MockFlagCache_Expecter) GetEvaluation(ctx interface{}, flagKey interface{}, projectID interface{}, envID interface{}) *MockFlagCache_GetEvaluation_Call {
	return &MockFlagCache_GetEvaluation_Call{Call: _e.mock.On("GetEvaluation", ctx, flagKey, projectID, envID)}
}

func (_c *MockFlagCache_GetEvaluation_Call) Run(run func(ctx context.Context, flagKey string, projectID uuid.UUID, envID uuid.UUID)) *MockFlagCache_GetEvaluation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockFlagCache_GetEvaluation_Call) Return(_a0 bool, _a1 error) *MockFlagCache_GetEvaluation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFlagCache_GetEvaluation_Call) RunAndReturn(run func(context.Context, string, uuid.UUID, uuid.UUID) (bool, error)) *MockFlagCache_GetEvaluation_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateFlag provides a mock function with given fields: ctx, flagKey, projectID
func (_m *MockFlagCache) InvalidateFlag(ctx context.Context, flagKey string, projectID uuid.UUID) error {
	ret := _m.Called(ctx, flagKey, projectID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateFlag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = rf(ctx, flagKey, projectID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFlagCache_InvalidateFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateFlag'
type MockFlagCache_InvalidateFlag_Call struct {
	*mock.Call
}

// InvalidateFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - flagKey string
//   - projectID uuid.UUID
func (_e *MockFlagCache_Expecter) InvalidateFlag(ctx interface{}, flagKey interface{}, projectID interface{}) *MockFlagCache_InvalidateFlag_Call {
	return &MockFlagCache_InvalidateFlag_Call{Call: _e.mock.On("InvalidateFlag", ctx, flagKey, projectID)}
}

func (_c *MockFlagCache_InvalidateFlag_Call) Run(run func(ctx context.Context, flagKey string, projectID uuid.UUID)) *MockFlagCache_InvalidateFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockFlagCache_InvalidateFlag_Call) Return(_a0 error) *MockFlagCache_InvalidateFlag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFlagCache_InvalidateFlag_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) error) *MockFlagCache_InvalidateFlag_Call {
	_c.Call.Return(run)
	return _c
}

// SetEvaluation provides a mock function with given fields: ctx, flagKey, projectID, envID, enabled
func (_m *MockFlagCache) SetEvaluation(ctx context.Context, flagKey string, projectID uuid.UUID, envID uuid.UUID, enabled bool) error {
	ret := _m.Called(ctx, flagKey, projectID, envID, enabled)

	if len(ret) == 0 {
		panic("no return value specified for SetEvaluation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, flagKey, projectID, envID, enabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFlagCache_SetEvaluation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEvaluation'
type MockFlagCache_SetEvaluation_Call struct {
	*mock.Call
}

// SetEvaluation is a helper method to define mock.On call
//   - ctx context.Context
//   - flagKey string
//   - projectID uuid.UUID
//   - envID uuid.UUID
//   - enabled bool
func (_e *MockFlagCache_Expecter) SetEvaluation(ctx interface{}, flagKey interface{}, projectID interface{}, envID interface{}, enabled interface{}) *MockFlagCache_SetEvaluation_Call {
	return &MockFlagCache_SetEvaluation_Call{Call: _e.mock.On("SetEvaluation", ctx, flagKey, projectID, envID, enabled)}
}

func (_c *MockFlagCache_SetEvaluation_Call) Run(run func(ctx context.Context, flagKey string, projectID uuid.UUID, envID uuid.UUID, enabled bool)) *MockFlagCache_SetEvaluation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(bool))
	})
	return _c
}

func (_c *MockFlagCache_SetEvaluation_Call) Return(_a0 error) *MockFlagCache_SetEvaluation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFlagCache_SetEvaluation_Call) RunAndReturn(run func(context.Context, string, uuid.UUID, uuid.UUID, bool) error) *MockFlagCache_SetEvaluation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFlagCache creates a new instance of MockFlagCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFlagCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFlagCache {
	mock := &MockFlagCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
