// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Royal17x/flagr/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockFlagRepository is an autogenerated mock type for the FlagRepository type
type MockFlagRepository struct {
	mock.Mock
}

type MockFlagRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFlagRepository) EXPECT() *MockFlagRepository_Expecter {
	return &MockFlagRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, flag
func (_m *MockFlagRepository) Create(ctx context.Context, flag *domain.Flag) (uuid.UUID, error) {
	ret := _m.Called(ctx, flag)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Flag) (uuid.UUID, error)); ok {
		return rf(ctx, flag)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Flag) uuid.UUID); ok {
		r0 = rf(ctx, flag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Flag) error); ok {
		r1 = rf(ctx, flag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFlagRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFlagRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - flag *domain.Flag
func (_e *MockFlagRepository_Expecter) Create(ctx interface{}, flag interface{}) *MockFlagRepository_Create_Call {
	return &MockFlagRepository_Create_Call{Call: _e.mock.On("Create", ctx, flag)}
}

func (_c *MockFlagRepository_Create_Call) Run(run func(ctx context.Context, flag *domain.Flag)) *MockFlagRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Flag))
	})
	return _c
}

func (_c *MockFlagRepository_Create_Call) Return(_a0 uuid.UUID, _a1 error) *MockFlagRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFlagRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Flag) (uuid.UUID, error)) *MockFlagRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockFlagRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFlagRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFlagRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockFlagRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockFlagRepository_Delete_Call {
	return &MockFlagRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockFlagRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockFlagRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFlagRepository_Delete_Call) Return(_a0 error) *MockFlagRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFlagRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockFlagRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockFlagRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Flag, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Flag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Flag, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Flag); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Flag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFlagRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockFlagRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockFlagRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockFlagRepository_GetByID_Call {
	return &MockFlagRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockFlagRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockFlagRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFlagRepository_GetByID_Call) Return(_a0 *domain.Flag, _a1 error) *MockFlagRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFlagRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Flag, error)) *MockFlagRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByKey provides a mock function with given fields: ctx, projectID, key
func (_m *MockFlagRepository) GetByKey(ctx context.Context, projectID uuid.UUID, key string) (*domain.Flag, error) {
	ret := _m.Called(ctx, projectID, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByKey")
	}

	var r0 *domain.Flag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*domain.Flag, error)); ok {
		return rf(ctx, projectID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *domain.Flag); ok {
		r0 = rf(ctx, projectID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Flag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, projectID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFlagRepository_GetByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByKey'
type MockFlagRepository_GetByKey_Call struct {
	*mock.Call
}

// GetByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
//   - key string
func (_e *MockFlagRepository_Expecter) GetByKey(ctx interface{}, projectID interface{}, key interface{}) *MockFlagRepository_GetByKey_Call {
	return &MockFlagRepository_GetByKey_Call{Call: _e.mock.On("GetByKey", ctx, projectID, key)}
}

func (_c *MockFlagRepository_GetByKey_Call) Run(run func(ctx context.Context, projectID uuid.UUID, key string)) *MockFlagRepository_GetByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockFlagRepository_GetByKey_Call) Return(_a0 *domain.Flag, _a1 error) *MockFlagRepository_GetByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFlagRepository_GetByKey_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*domain.Flag, error)) *MockFlagRepository_GetByKey_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, projectID
func (_m *MockFlagRepository) List(ctx context.Context, projectID uuid.UUID) ([]*domain.Flag, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Flag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Flag, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Flag); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Flag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFlagRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockFlagRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
func (_e *MockFlagRepository_Expecter) List(ctx interface{}, projectID interface{}) *MockFlagRepository_List_Call {
	return &MockFlagRepository_List_Call{Call: _e.mock.On("List", ctx, projectID)}
}

func (_c *MockFlagRepository_List_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockFlagRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFlagRepository_List_Call) Return(_a0 []*domain.Flag, _a1 error) *MockFlagRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFlagRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.Flag, error)) *MockFlagRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, flag
func (_m *MockFlagRepository) Update(ctx context.Context, flag *domain.Flag) error {
	ret := _m.Called(ctx, flag)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Flag) error); ok {
		r0 = rf(ctx, flag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFlagRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockFlagRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - flag *domain.Flag
func (_e *MockFlagRepository_Expecter) Update(ctx interface{}, flag interface{}) *MockFlagRepository_Update_Call {
	return &MockFlagRepository_Update_Call{Call: _e.mock.On("Update", ctx, flag)}
}

func (_c *MockFlagRepository_Update_Call) Run(run func(ctx context.Context, flag *domain.Flag)) *MockFlagRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Flag))
	})
	return _c
}

func (_c *MockFlagRepository_Update_Call) Return(_a0 error) *MockFlagRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFlagRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Flag) error) *MockFlagRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFlagRepository creates a new instance of MockFlagRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFlagRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFlagRepository {
	mock := &MockFlagRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
